name: test & release

on: push

jobs:
  test:
    name: test & release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Test
        run: make test
      - name: Build artifact
        if: startsWith(github.ref, 'refs/tags/')
        run: make build
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: '*.alfredworkflow'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
